### ISSUE TITLE
Prepare the final big release for Second Edition

### ISSUE THREAD

**Issue by UrsKR** [anathema/anathema#328]
##### Must
- [x] Update to J7u21 (new Equipment UI won't work flawlessly otherwise)
- [x] Update OS X build to J7u21
- [x] Force re-download of JREs on Jenkins to ensure it uses the correct version
- [x] Include Scribe manual in freshly created repositories (people need it to operate it)
- [x] Fix re-typing issue in Scribe
- [x] Check Shortcuts on Windows
- [x] Fix Equipment Database on OS X in #330
- [x] Fix Menu Bar on OS X in #332 
- [x] Check new UI on Linux (we shouldn't alienate our friends on other systems more than necessary)
- [x] Fix "Delete Item" on OS X in #335 
- [x] Fix "New Item" on OS X in #336 
##### Should
- [x] Restore the icons on rear-removal buttons (e.g. Backgrounds)
- [x] Convert notes to scrolls
- [x] Find proper icon for Scribe
- [x] Make icons inside Scribe consistent with the rest of Anathema
- [x] Fix Edit Stats in #340 
##### Could
- [ ] Restore warning when unsaved changes would be discarded by a selection in Equipment Database in #337 
- [ ] Don't show item as selected in Equipment Database after deleting the previous item
- [ ] Don't allow duplication of freshly created, unsaved items in Equipment Database
- [ ] Use List instead of Buttons in Scribe
- [ ] Use List instead of Buttons in Character
- [ ] Disable the XP button for Spirits
- [ ] Add button to delete Characters
- [ ] Show ControlledReportTool in a Dropdown instead of Dialog
- [ ] Add Save All for Characters
- [ ] Add a Help button to show the explanatory scroll
